# @package _global_
defaults:
  - vlabench_select_book_rothko_3cam192_wan21
  - _self_
output_dir: ./runs/vlabench_select_book_rothko_all_absolute_3cam192_wan21/${now:%Y-%m-%d}_${now:%H-%M-%S}
data:
  train:
    raymap_representation: vlabench_rothko_all_absolute
    latent_cache_dir: ./data/vlabench_select_book_rothko_all_absolute_all10bounds_3cam192_wan21_bf16_h16_latents
    rothko_norm_stats: ./data/vlabench_primitive_ft_lerobot/norm_stats/vlabench_rothko_all_absolute_minmax_margin01_h16_192x576_centerfrac05_train99_all10.pt
    pretrained_norm_stats: ./data/vlabench_primitive_ft_lerobot/norm_stats/vlabench_rothko_all_absolute_minmax_margin01_h16_192x576_centerfrac05_train99_all10.json
    rothko_config:
      frame0_pose_mode: absolute
      absolute_position_min: [-0.486968914270401, -0.06711820721626281, -0.023272830285131933]
      absolute_position_max: [0.4814973866939545, 0.812754819393158, 0.6373460388183594]
  val:
    raymap_representation: ${data.train.raymap_representation}
model:
  raymap_representation: ${data.train.raymap_representation}
  vae_safetensors_path: null
wandb:
  name: vlabench_select_book_rothko_all_absolute_3cam192_wan21
