# @package _global_
defaults:
  - vlabench_rothko_2cam224_full_wan22_5b_1e-4
  - override /model: fastwam_video_only_vlabench_rothko_wan21_1_3b
  - _self_

output_dir: ./runs/vlabench_rothko_2cam224_full_wan21_1_3b_1e-4/${now:%Y-%m-%d}_${now:%H-%M-%S}
wandb:
  name: vlabench_rothko_2cam224_full_wan21_1_3b_1e-4
